name: functional_data
packages:
  - functional_data
  - functional_data_generator
  - example
scripts:
  get: melos exec -- dart pub get

  generate:dart:
    run: melos exec -c 1 --depends-on="build_runner" --no-flutter -- "dart run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Dart packages in this project.
