name: functional_data

packages:
  - functional_data
  - functional_data_generator
  - example

scripts:
  get: melos exec -- dart pub get

  generate:dart:
    description: Build all generated files for Dart packages in this project.
    steps:
      - melos exec -c 1 --depends-on="build_runner" --no-flutter -- "dart run build_runner build --delete-conflicting-outputs"
      - melos exec dart format --line-length 120 .

  format120:
    run: melos exec dart format --line-length 120 .
